// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using EchoBot.Models;
//
//    var dialogflowResponse = DialogflowResponse.FromJson(jsonString);

namespace EchoBot.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class QnAMakerResponse
    {
        [JsonProperty("answers")]
        public Answer[] Answers { get; set; }
    }

    public partial class Answer
    {
        [JsonProperty("questions")]
        public string[] Questions { get; set; }

        [JsonProperty("answer")]
        public string AnswerText { get; set; }

        [JsonProperty("score")]
        public double Score { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("source")]
        public Uri Source { get; set; }

        [JsonProperty("metadata")]
        public object[] Metadata { get; set; }
    }

    public partial class QnAMakerResponse
    {
        public static QnAMakerResponse FromJson(string json) => JsonConvert.DeserializeObject<QnAMakerResponse>(json, EchoBot.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this QnAMakerResponse self) => JsonConvert.SerializeObject(self, EchoBot.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
